package com.mallcai.domain.dto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TblHqProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public TblHqProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHqProductIdIsNull() {
            addCriterion("hq_product_id is null");
            return (Criteria) this;
        }

        public Criteria andHqProductIdIsNotNull() {
            addCriterion("hq_product_id is not null");
            return (Criteria) this;
        }

        public Criteria andHqProductIdEqualTo(Integer value) {
            addCriterion("hq_product_id =", value, "hqProductId");
            return (Criteria) this;
        }

        public Criteria andHqProductIdNotEqualTo(Integer value) {
            addCriterion("hq_product_id <>", value, "hqProductId");
            return (Criteria) this;
        }

        public Criteria andHqProductIdGreaterThan(Integer value) {
            addCriterion("hq_product_id >", value, "hqProductId");
            return (Criteria) this;
        }

        public Criteria andHqProductIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("hq_product_id >=", value, "hqProductId");
            return (Criteria) this;
        }

        public Criteria andHqProductIdLessThan(Integer value) {
            addCriterion("hq_product_id <", value, "hqProductId");
            return (Criteria) this;
        }

        public Criteria andHqProductIdLessThanOrEqualTo(Integer value) {
            addCriterion("hq_product_id <=", value, "hqProductId");
            return (Criteria) this;
        }

        public Criteria andHqProductIdIn(List<Integer> values) {
            addCriterion("hq_product_id in", values, "hqProductId");
            return (Criteria) this;
        }

        public Criteria andHqProductIdNotIn(List<Integer> values) {
            addCriterion("hq_product_id not in", values, "hqProductId");
            return (Criteria) this;
        }

        public Criteria andHqProductIdBetween(Integer value1, Integer value2) {
            addCriterion("hq_product_id between", value1, value2, "hqProductId");
            return (Criteria) this;
        }

        public Criteria andHqProductIdNotBetween(Integer value1, Integer value2) {
            addCriterion("hq_product_id not between", value1, value2, "hqProductId");
            return (Criteria) this;
        }

        public Criteria andClassifyIdIsNull() {
            addCriterion("classify_id is null");
            return (Criteria) this;
        }

        public Criteria andClassifyIdIsNotNull() {
            addCriterion("classify_id is not null");
            return (Criteria) this;
        }

        public Criteria andClassifyIdEqualTo(Integer value) {
            addCriterion("classify_id =", value, "classifyId");
            return (Criteria) this;
        }

        public Criteria andClassifyIdNotEqualTo(Integer value) {
            addCriterion("classify_id <>", value, "classifyId");
            return (Criteria) this;
        }

        public Criteria andClassifyIdGreaterThan(Integer value) {
            addCriterion("classify_id >", value, "classifyId");
            return (Criteria) this;
        }

        public Criteria andClassifyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("classify_id >=", value, "classifyId");
            return (Criteria) this;
        }

        public Criteria andClassifyIdLessThan(Integer value) {
            addCriterion("classify_id <", value, "classifyId");
            return (Criteria) this;
        }

        public Criteria andClassifyIdLessThanOrEqualTo(Integer value) {
            addCriterion("classify_id <=", value, "classifyId");
            return (Criteria) this;
        }

        public Criteria andClassifyIdIn(List<Integer> values) {
            addCriterion("classify_id in", values, "classifyId");
            return (Criteria) this;
        }

        public Criteria andClassifyIdNotIn(List<Integer> values) {
            addCriterion("classify_id not in", values, "classifyId");
            return (Criteria) this;
        }

        public Criteria andClassifyIdBetween(Integer value1, Integer value2) {
            addCriterion("classify_id between", value1, value2, "classifyId");
            return (Criteria) this;
        }

        public Criteria andClassifyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("classify_id not between", value1, value2, "classifyId");
            return (Criteria) this;
        }

        public Criteria andProductNoIsNull() {
            addCriterion("product_no is null");
            return (Criteria) this;
        }

        public Criteria andProductNoIsNotNull() {
            addCriterion("product_no is not null");
            return (Criteria) this;
        }

        public Criteria andProductNoEqualTo(String value) {
            addCriterion("product_no =", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotEqualTo(String value) {
            addCriterion("product_no <>", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoGreaterThan(String value) {
            addCriterion("product_no >", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoGreaterThanOrEqualTo(String value) {
            addCriterion("product_no >=", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoLessThan(String value) {
            addCriterion("product_no <", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoLessThanOrEqualTo(String value) {
            addCriterion("product_no <=", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoLike(String value) {
            addCriterion("product_no like", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotLike(String value) {
            addCriterion("product_no not like", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoIn(List<String> values) {
            addCriterion("product_no in", values, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotIn(List<String> values) {
            addCriterion("product_no not in", values, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoBetween(String value1, String value2) {
            addCriterion("product_no between", value1, value2, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotBetween(String value1, String value2) {
            addCriterion("product_no not between", value1, value2, "productNo");
            return (Criteria) this;
        }

        public Criteria andHqProductNameIsNull() {
            addCriterion("hq_product_name is null");
            return (Criteria) this;
        }

        public Criteria andHqProductNameIsNotNull() {
            addCriterion("hq_product_name is not null");
            return (Criteria) this;
        }

        public Criteria andHqProductNameEqualTo(String value) {
            addCriterion("hq_product_name =", value, "hqProductName");
            return (Criteria) this;
        }

        public Criteria andHqProductNameNotEqualTo(String value) {
            addCriterion("hq_product_name <>", value, "hqProductName");
            return (Criteria) this;
        }

        public Criteria andHqProductNameGreaterThan(String value) {
            addCriterion("hq_product_name >", value, "hqProductName");
            return (Criteria) this;
        }

        public Criteria andHqProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("hq_product_name >=", value, "hqProductName");
            return (Criteria) this;
        }

        public Criteria andHqProductNameLessThan(String value) {
            addCriterion("hq_product_name <", value, "hqProductName");
            return (Criteria) this;
        }

        public Criteria andHqProductNameLessThanOrEqualTo(String value) {
            addCriterion("hq_product_name <=", value, "hqProductName");
            return (Criteria) this;
        }

        public Criteria andHqProductNameLike(String value) {
            addCriterion("hq_product_name like", value, "hqProductName");
            return (Criteria) this;
        }

        public Criteria andHqProductNameNotLike(String value) {
            addCriterion("hq_product_name not like", value, "hqProductName");
            return (Criteria) this;
        }

        public Criteria andHqProductNameIn(List<String> values) {
            addCriterion("hq_product_name in", values, "hqProductName");
            return (Criteria) this;
        }

        public Criteria andHqProductNameNotIn(List<String> values) {
            addCriterion("hq_product_name not in", values, "hqProductName");
            return (Criteria) this;
        }

        public Criteria andHqProductNameBetween(String value1, String value2) {
            addCriterion("hq_product_name between", value1, value2, "hqProductName");
            return (Criteria) this;
        }

        public Criteria andHqProductNameNotBetween(String value1, String value2) {
            addCriterion("hq_product_name not between", value1, value2, "hqProductName");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeIsNull() {
            addCriterion("delivery_mode is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeIsNotNull() {
            addCriterion("delivery_mode is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeEqualTo(Byte value) {
            addCriterion("delivery_mode =", value, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeNotEqualTo(Byte value) {
            addCriterion("delivery_mode <>", value, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeGreaterThan(Byte value) {
            addCriterion("delivery_mode >", value, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeGreaterThanOrEqualTo(Byte value) {
            addCriterion("delivery_mode >=", value, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeLessThan(Byte value) {
            addCriterion("delivery_mode <", value, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeLessThanOrEqualTo(Byte value) {
            addCriterion("delivery_mode <=", value, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeIn(List<Byte> values) {
            addCriterion("delivery_mode in", values, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeNotIn(List<Byte> values) {
            addCriterion("delivery_mode not in", values, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeBetween(Byte value1, Byte value2) {
            addCriterion("delivery_mode between", value1, value2, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeNotBetween(Byte value1, Byte value2) {
            addCriterion("delivery_mode not between", value1, value2, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andHqProductIconIsNull() {
            addCriterion("hq_product_icon is null");
            return (Criteria) this;
        }

        public Criteria andHqProductIconIsNotNull() {
            addCriterion("hq_product_icon is not null");
            return (Criteria) this;
        }

        public Criteria andHqProductIconEqualTo(String value) {
            addCriterion("hq_product_icon =", value, "hqProductIcon");
            return (Criteria) this;
        }

        public Criteria andHqProductIconNotEqualTo(String value) {
            addCriterion("hq_product_icon <>", value, "hqProductIcon");
            return (Criteria) this;
        }

        public Criteria andHqProductIconGreaterThan(String value) {
            addCriterion("hq_product_icon >", value, "hqProductIcon");
            return (Criteria) this;
        }

        public Criteria andHqProductIconGreaterThanOrEqualTo(String value) {
            addCriterion("hq_product_icon >=", value, "hqProductIcon");
            return (Criteria) this;
        }

        public Criteria andHqProductIconLessThan(String value) {
            addCriterion("hq_product_icon <", value, "hqProductIcon");
            return (Criteria) this;
        }

        public Criteria andHqProductIconLessThanOrEqualTo(String value) {
            addCriterion("hq_product_icon <=", value, "hqProductIcon");
            return (Criteria) this;
        }

        public Criteria andHqProductIconLike(String value) {
            addCriterion("hq_product_icon like", value, "hqProductIcon");
            return (Criteria) this;
        }

        public Criteria andHqProductIconNotLike(String value) {
            addCriterion("hq_product_icon not like", value, "hqProductIcon");
            return (Criteria) this;
        }

        public Criteria andHqProductIconIn(List<String> values) {
            addCriterion("hq_product_icon in", values, "hqProductIcon");
            return (Criteria) this;
        }

        public Criteria andHqProductIconNotIn(List<String> values) {
            addCriterion("hq_product_icon not in", values, "hqProductIcon");
            return (Criteria) this;
        }

        public Criteria andHqProductIconBetween(String value1, String value2) {
            addCriterion("hq_product_icon between", value1, value2, "hqProductIcon");
            return (Criteria) this;
        }

        public Criteria andHqProductIconNotBetween(String value1, String value2) {
            addCriterion("hq_product_icon not between", value1, value2, "hqProductIcon");
            return (Criteria) this;
        }

        public Criteria andHqProductPicIsNull() {
            addCriterion("hq_product_pic is null");
            return (Criteria) this;
        }

        public Criteria andHqProductPicIsNotNull() {
            addCriterion("hq_product_pic is not null");
            return (Criteria) this;
        }

        public Criteria andHqProductPicEqualTo(String value) {
            addCriterion("hq_product_pic =", value, "hqProductPic");
            return (Criteria) this;
        }

        public Criteria andHqProductPicNotEqualTo(String value) {
            addCriterion("hq_product_pic <>", value, "hqProductPic");
            return (Criteria) this;
        }

        public Criteria andHqProductPicGreaterThan(String value) {
            addCriterion("hq_product_pic >", value, "hqProductPic");
            return (Criteria) this;
        }

        public Criteria andHqProductPicGreaterThanOrEqualTo(String value) {
            addCriterion("hq_product_pic >=", value, "hqProductPic");
            return (Criteria) this;
        }

        public Criteria andHqProductPicLessThan(String value) {
            addCriterion("hq_product_pic <", value, "hqProductPic");
            return (Criteria) this;
        }

        public Criteria andHqProductPicLessThanOrEqualTo(String value) {
            addCriterion("hq_product_pic <=", value, "hqProductPic");
            return (Criteria) this;
        }

        public Criteria andHqProductPicLike(String value) {
            addCriterion("hq_product_pic like", value, "hqProductPic");
            return (Criteria) this;
        }

        public Criteria andHqProductPicNotLike(String value) {
            addCriterion("hq_product_pic not like", value, "hqProductPic");
            return (Criteria) this;
        }

        public Criteria andHqProductPicIn(List<String> values) {
            addCriterion("hq_product_pic in", values, "hqProductPic");
            return (Criteria) this;
        }

        public Criteria andHqProductPicNotIn(List<String> values) {
            addCriterion("hq_product_pic not in", values, "hqProductPic");
            return (Criteria) this;
        }

        public Criteria andHqProductPicBetween(String value1, String value2) {
            addCriterion("hq_product_pic between", value1, value2, "hqProductPic");
            return (Criteria) this;
        }

        public Criteria andHqProductPicNotBetween(String value1, String value2) {
            addCriterion("hq_product_pic not between", value1, value2, "hqProductPic");
            return (Criteria) this;
        }

        public Criteria andLocalizeFlagIsNull() {
            addCriterion("localize_flag is null");
            return (Criteria) this;
        }

        public Criteria andLocalizeFlagIsNotNull() {
            addCriterion("localize_flag is not null");
            return (Criteria) this;
        }

        public Criteria andLocalizeFlagEqualTo(Byte value) {
            addCriterion("localize_flag =", value, "localizeFlag");
            return (Criteria) this;
        }

        public Criteria andLocalizeFlagNotEqualTo(Byte value) {
            addCriterion("localize_flag <>", value, "localizeFlag");
            return (Criteria) this;
        }

        public Criteria andLocalizeFlagGreaterThan(Byte value) {
            addCriterion("localize_flag >", value, "localizeFlag");
            return (Criteria) this;
        }

        public Criteria andLocalizeFlagGreaterThanOrEqualTo(Byte value) {
            addCriterion("localize_flag >=", value, "localizeFlag");
            return (Criteria) this;
        }

        public Criteria andLocalizeFlagLessThan(Byte value) {
            addCriterion("localize_flag <", value, "localizeFlag");
            return (Criteria) this;
        }

        public Criteria andLocalizeFlagLessThanOrEqualTo(Byte value) {
            addCriterion("localize_flag <=", value, "localizeFlag");
            return (Criteria) this;
        }

        public Criteria andLocalizeFlagIn(List<Byte> values) {
            addCriterion("localize_flag in", values, "localizeFlag");
            return (Criteria) this;
        }

        public Criteria andLocalizeFlagNotIn(List<Byte> values) {
            addCriterion("localize_flag not in", values, "localizeFlag");
            return (Criteria) this;
        }

        public Criteria andLocalizeFlagBetween(Byte value1, Byte value2) {
            addCriterion("localize_flag between", value1, value2, "localizeFlag");
            return (Criteria) this;
        }

        public Criteria andLocalizeFlagNotBetween(Byte value1, Byte value2) {
            addCriterion("localize_flag not between", value1, value2, "localizeFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Byte value) {
            addCriterion("del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Byte value) {
            addCriterion("del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Byte value) {
            addCriterion("del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Byte value) {
            addCriterion("del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Byte value) {
            addCriterion("del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Byte value) {
            addCriterion("del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Byte> values) {
            addCriterion("del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Byte> values) {
            addCriterion("del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Byte value1, Byte value2) {
            addCriterion("del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Byte value1, Byte value2) {
            addCriterion("del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Integer value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Integer value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Integer value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Integer value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Integer> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Integer> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Integer value1, Integer value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(Integer value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(Integer value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(Integer value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(Integer value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<Integer> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<Integer> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(Integer value1, Integer value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andBarCodeIsNull() {
            addCriterion("bar_code is null");
            return (Criteria) this;
        }

        public Criteria andBarCodeIsNotNull() {
            addCriterion("bar_code is not null");
            return (Criteria) this;
        }

        public Criteria andBarCodeEqualTo(String value) {
            addCriterion("bar_code =", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeNotEqualTo(String value) {
            addCriterion("bar_code <>", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeGreaterThan(String value) {
            addCriterion("bar_code >", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeGreaterThanOrEqualTo(String value) {
            addCriterion("bar_code >=", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeLessThan(String value) {
            addCriterion("bar_code <", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeLessThanOrEqualTo(String value) {
            addCriterion("bar_code <=", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeLike(String value) {
            addCriterion("bar_code like", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeNotLike(String value) {
            addCriterion("bar_code not like", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeIn(List<String> values) {
            addCriterion("bar_code in", values, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeNotIn(List<String> values) {
            addCriterion("bar_code not in", values, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeBetween(String value1, String value2) {
            addCriterion("bar_code between", value1, value2, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeNotBetween(String value1, String value2) {
            addCriterion("bar_code not between", value1, value2, "barCode");
            return (Criteria) this;
        }

        public Criteria andKeepTypeIsNull() {
            addCriterion("keep_type is null");
            return (Criteria) this;
        }

        public Criteria andKeepTypeIsNotNull() {
            addCriterion("keep_type is not null");
            return (Criteria) this;
        }

        public Criteria andKeepTypeEqualTo(Integer value) {
            addCriterion("keep_type =", value, "keepType");
            return (Criteria) this;
        }

        public Criteria andKeepTypeNotEqualTo(Integer value) {
            addCriterion("keep_type <>", value, "keepType");
            return (Criteria) this;
        }

        public Criteria andKeepTypeGreaterThan(Integer value) {
            addCriterion("keep_type >", value, "keepType");
            return (Criteria) this;
        }

        public Criteria andKeepTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("keep_type >=", value, "keepType");
            return (Criteria) this;
        }

        public Criteria andKeepTypeLessThan(Integer value) {
            addCriterion("keep_type <", value, "keepType");
            return (Criteria) this;
        }

        public Criteria andKeepTypeLessThanOrEqualTo(Integer value) {
            addCriterion("keep_type <=", value, "keepType");
            return (Criteria) this;
        }

        public Criteria andKeepTypeIn(List<Integer> values) {
            addCriterion("keep_type in", values, "keepType");
            return (Criteria) this;
        }

        public Criteria andKeepTypeNotIn(List<Integer> values) {
            addCriterion("keep_type not in", values, "keepType");
            return (Criteria) this;
        }

        public Criteria andKeepTypeBetween(Integer value1, Integer value2) {
            addCriterion("keep_type between", value1, value2, "keepType");
            return (Criteria) this;
        }

        public Criteria andKeepTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("keep_type not between", value1, value2, "keepType");
            return (Criteria) this;
        }

        public Criteria andQualityTimeIsNull() {
            addCriterion("quality_time is null");
            return (Criteria) this;
        }

        public Criteria andQualityTimeIsNotNull() {
            addCriterion("quality_time is not null");
            return (Criteria) this;
        }

        public Criteria andQualityTimeEqualTo(Integer value) {
            addCriterion("quality_time =", value, "qualityTime");
            return (Criteria) this;
        }

        public Criteria andQualityTimeNotEqualTo(Integer value) {
            addCriterion("quality_time <>", value, "qualityTime");
            return (Criteria) this;
        }

        public Criteria andQualityTimeGreaterThan(Integer value) {
            addCriterion("quality_time >", value, "qualityTime");
            return (Criteria) this;
        }

        public Criteria andQualityTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("quality_time >=", value, "qualityTime");
            return (Criteria) this;
        }

        public Criteria andQualityTimeLessThan(Integer value) {
            addCriterion("quality_time <", value, "qualityTime");
            return (Criteria) this;
        }

        public Criteria andQualityTimeLessThanOrEqualTo(Integer value) {
            addCriterion("quality_time <=", value, "qualityTime");
            return (Criteria) this;
        }

        public Criteria andQualityTimeIn(List<Integer> values) {
            addCriterion("quality_time in", values, "qualityTime");
            return (Criteria) this;
        }

        public Criteria andQualityTimeNotIn(List<Integer> values) {
            addCriterion("quality_time not in", values, "qualityTime");
            return (Criteria) this;
        }

        public Criteria andQualityTimeBetween(Integer value1, Integer value2) {
            addCriterion("quality_time between", value1, value2, "qualityTime");
            return (Criteria) this;
        }

        public Criteria andQualityTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("quality_time not between", value1, value2, "qualityTime");
            return (Criteria) this;
        }

        public Criteria andIsStandardIsNull() {
            addCriterion("is_standard is null");
            return (Criteria) this;
        }

        public Criteria andIsStandardIsNotNull() {
            addCriterion("is_standard is not null");
            return (Criteria) this;
        }

        public Criteria andIsStandardEqualTo(Integer value) {
            addCriterion("is_standard =", value, "isStandard");
            return (Criteria) this;
        }

        public Criteria andIsStandardNotEqualTo(Integer value) {
            addCriterion("is_standard <>", value, "isStandard");
            return (Criteria) this;
        }

        public Criteria andIsStandardGreaterThan(Integer value) {
            addCriterion("is_standard >", value, "isStandard");
            return (Criteria) this;
        }

        public Criteria andIsStandardGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_standard >=", value, "isStandard");
            return (Criteria) this;
        }

        public Criteria andIsStandardLessThan(Integer value) {
            addCriterion("is_standard <", value, "isStandard");
            return (Criteria) this;
        }

        public Criteria andIsStandardLessThanOrEqualTo(Integer value) {
            addCriterion("is_standard <=", value, "isStandard");
            return (Criteria) this;
        }

        public Criteria andIsStandardIn(List<Integer> values) {
            addCriterion("is_standard in", values, "isStandard");
            return (Criteria) this;
        }

        public Criteria andIsStandardNotIn(List<Integer> values) {
            addCriterion("is_standard not in", values, "isStandard");
            return (Criteria) this;
        }

        public Criteria andIsStandardBetween(Integer value1, Integer value2) {
            addCriterion("is_standard between", value1, value2, "isStandard");
            return (Criteria) this;
        }

        public Criteria andIsStandardNotBetween(Integer value1, Integer value2) {
            addCriterion("is_standard not between", value1, value2, "isStandard");
            return (Criteria) this;
        }

        public Criteria andPickClassifyIsNull() {
            addCriterion("pick_classify is null");
            return (Criteria) this;
        }

        public Criteria andPickClassifyIsNotNull() {
            addCriterion("pick_classify is not null");
            return (Criteria) this;
        }

        public Criteria andPickClassifyEqualTo(Integer value) {
            addCriterion("pick_classify =", value, "pickClassify");
            return (Criteria) this;
        }

        public Criteria andPickClassifyNotEqualTo(Integer value) {
            addCriterion("pick_classify <>", value, "pickClassify");
            return (Criteria) this;
        }

        public Criteria andPickClassifyGreaterThan(Integer value) {
            addCriterion("pick_classify >", value, "pickClassify");
            return (Criteria) this;
        }

        public Criteria andPickClassifyGreaterThanOrEqualTo(Integer value) {
            addCriterion("pick_classify >=", value, "pickClassify");
            return (Criteria) this;
        }

        public Criteria andPickClassifyLessThan(Integer value) {
            addCriterion("pick_classify <", value, "pickClassify");
            return (Criteria) this;
        }

        public Criteria andPickClassifyLessThanOrEqualTo(Integer value) {
            addCriterion("pick_classify <=", value, "pickClassify");
            return (Criteria) this;
        }

        public Criteria andPickClassifyIn(List<Integer> values) {
            addCriterion("pick_classify in", values, "pickClassify");
            return (Criteria) this;
        }

        public Criteria andPickClassifyNotIn(List<Integer> values) {
            addCriterion("pick_classify not in", values, "pickClassify");
            return (Criteria) this;
        }

        public Criteria andPickClassifyBetween(Integer value1, Integer value2) {
            addCriterion("pick_classify between", value1, value2, "pickClassify");
            return (Criteria) this;
        }

        public Criteria andPickClassifyNotBetween(Integer value1, Integer value2) {
            addCriterion("pick_classify not between", value1, value2, "pickClassify");
            return (Criteria) this;
        }

        public Criteria andProductRateIsNull() {
            addCriterion("product_rate is null");
            return (Criteria) this;
        }

        public Criteria andProductRateIsNotNull() {
            addCriterion("product_rate is not null");
            return (Criteria) this;
        }

        public Criteria andProductRateEqualTo(BigDecimal value) {
            addCriterion("product_rate =", value, "productRate");
            return (Criteria) this;
        }

        public Criteria andProductRateNotEqualTo(BigDecimal value) {
            addCriterion("product_rate <>", value, "productRate");
            return (Criteria) this;
        }

        public Criteria andProductRateGreaterThan(BigDecimal value) {
            addCriterion("product_rate >", value, "productRate");
            return (Criteria) this;
        }

        public Criteria andProductRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("product_rate >=", value, "productRate");
            return (Criteria) this;
        }

        public Criteria andProductRateLessThan(BigDecimal value) {
            addCriterion("product_rate <", value, "productRate");
            return (Criteria) this;
        }

        public Criteria andProductRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("product_rate <=", value, "productRate");
            return (Criteria) this;
        }

        public Criteria andProductRateIn(List<BigDecimal> values) {
            addCriterion("product_rate in", values, "productRate");
            return (Criteria) this;
        }

        public Criteria andProductRateNotIn(List<BigDecimal> values) {
            addCriterion("product_rate not in", values, "productRate");
            return (Criteria) this;
        }

        public Criteria andProductRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("product_rate between", value1, value2, "productRate");
            return (Criteria) this;
        }

        public Criteria andProductRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("product_rate not between", value1, value2, "productRate");
            return (Criteria) this;
        }

        public Criteria andLengthIsNull() {
            addCriterion("length is null");
            return (Criteria) this;
        }

        public Criteria andLengthIsNotNull() {
            addCriterion("length is not null");
            return (Criteria) this;
        }

        public Criteria andLengthEqualTo(String value) {
            addCriterion("length =", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotEqualTo(String value) {
            addCriterion("length <>", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthGreaterThan(String value) {
            addCriterion("length >", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthGreaterThanOrEqualTo(String value) {
            addCriterion("length >=", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthLessThan(String value) {
            addCriterion("length <", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthLessThanOrEqualTo(String value) {
            addCriterion("length <=", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthLike(String value) {
            addCriterion("length like", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotLike(String value) {
            addCriterion("length not like", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthIn(List<String> values) {
            addCriterion("length in", values, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotIn(List<String> values) {
            addCriterion("length not in", values, "length");
            return (Criteria) this;
        }

        public Criteria andLengthBetween(String value1, String value2) {
            addCriterion("length between", value1, value2, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotBetween(String value1, String value2) {
            addCriterion("length not between", value1, value2, "length");
            return (Criteria) this;
        }

        public Criteria andWideIsNull() {
            addCriterion("wide is null");
            return (Criteria) this;
        }

        public Criteria andWideIsNotNull() {
            addCriterion("wide is not null");
            return (Criteria) this;
        }

        public Criteria andWideEqualTo(String value) {
            addCriterion("wide =", value, "wide");
            return (Criteria) this;
        }

        public Criteria andWideNotEqualTo(String value) {
            addCriterion("wide <>", value, "wide");
            return (Criteria) this;
        }

        public Criteria andWideGreaterThan(String value) {
            addCriterion("wide >", value, "wide");
            return (Criteria) this;
        }

        public Criteria andWideGreaterThanOrEqualTo(String value) {
            addCriterion("wide >=", value, "wide");
            return (Criteria) this;
        }

        public Criteria andWideLessThan(String value) {
            addCriterion("wide <", value, "wide");
            return (Criteria) this;
        }

        public Criteria andWideLessThanOrEqualTo(String value) {
            addCriterion("wide <=", value, "wide");
            return (Criteria) this;
        }

        public Criteria andWideLike(String value) {
            addCriterion("wide like", value, "wide");
            return (Criteria) this;
        }

        public Criteria andWideNotLike(String value) {
            addCriterion("wide not like", value, "wide");
            return (Criteria) this;
        }

        public Criteria andWideIn(List<String> values) {
            addCriterion("wide in", values, "wide");
            return (Criteria) this;
        }

        public Criteria andWideNotIn(List<String> values) {
            addCriterion("wide not in", values, "wide");
            return (Criteria) this;
        }

        public Criteria andWideBetween(String value1, String value2) {
            addCriterion("wide between", value1, value2, "wide");
            return (Criteria) this;
        }

        public Criteria andWideNotBetween(String value1, String value2) {
            addCriterion("wide not between", value1, value2, "wide");
            return (Criteria) this;
        }

        public Criteria andHighIsNull() {
            addCriterion("high is null");
            return (Criteria) this;
        }

        public Criteria andHighIsNotNull() {
            addCriterion("high is not null");
            return (Criteria) this;
        }

        public Criteria andHighEqualTo(String value) {
            addCriterion("high =", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighNotEqualTo(String value) {
            addCriterion("high <>", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighGreaterThan(String value) {
            addCriterion("high >", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighGreaterThanOrEqualTo(String value) {
            addCriterion("high >=", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighLessThan(String value) {
            addCriterion("high <", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighLessThanOrEqualTo(String value) {
            addCriterion("high <=", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighLike(String value) {
            addCriterion("high like", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighNotLike(String value) {
            addCriterion("high not like", value, "high");
            return (Criteria) this;
        }

        public Criteria andHighIn(List<String> values) {
            addCriterion("high in", values, "high");
            return (Criteria) this;
        }

        public Criteria andHighNotIn(List<String> values) {
            addCriterion("high not in", values, "high");
            return (Criteria) this;
        }

        public Criteria andHighBetween(String value1, String value2) {
            addCriterion("high between", value1, value2, "high");
            return (Criteria) this;
        }

        public Criteria andHighNotBetween(String value1, String value2) {
            addCriterion("high not between", value1, value2, "high");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIsNull() {
            addCriterion("goods_type is null");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIsNotNull() {
            addCriterion("goods_type is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeEqualTo(Byte value) {
            addCriterion("goods_type =", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeNotEqualTo(Byte value) {
            addCriterion("goods_type <>", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeGreaterThan(Byte value) {
            addCriterion("goods_type >", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("goods_type >=", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeLessThan(Byte value) {
            addCriterion("goods_type <", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeLessThanOrEqualTo(Byte value) {
            addCriterion("goods_type <=", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIn(List<Byte> values) {
            addCriterion("goods_type in", values, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeNotIn(List<Byte> values) {
            addCriterion("goods_type not in", values, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeBetween(Byte value1, Byte value2) {
            addCriterion("goods_type between", value1, value2, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("goods_type not between", value1, value2, "goodsType");
            return (Criteria) this;
        }

        public Criteria andProductTaxIdIsNull() {
            addCriterion("product_tax_id is null");
            return (Criteria) this;
        }

        public Criteria andProductTaxIdIsNotNull() {
            addCriterion("product_tax_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductTaxIdEqualTo(Integer value) {
            addCriterion("product_tax_id =", value, "productTaxId");
            return (Criteria) this;
        }

        public Criteria andProductTaxIdNotEqualTo(Integer value) {
            addCriterion("product_tax_id <>", value, "productTaxId");
            return (Criteria) this;
        }

        public Criteria andProductTaxIdGreaterThan(Integer value) {
            addCriterion("product_tax_id >", value, "productTaxId");
            return (Criteria) this;
        }

        public Criteria andProductTaxIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_tax_id >=", value, "productTaxId");
            return (Criteria) this;
        }

        public Criteria andProductTaxIdLessThan(Integer value) {
            addCriterion("product_tax_id <", value, "productTaxId");
            return (Criteria) this;
        }

        public Criteria andProductTaxIdLessThanOrEqualTo(Integer value) {
            addCriterion("product_tax_id <=", value, "productTaxId");
            return (Criteria) this;
        }

        public Criteria andProductTaxIdIn(List<Integer> values) {
            addCriterion("product_tax_id in", values, "productTaxId");
            return (Criteria) this;
        }

        public Criteria andProductTaxIdNotIn(List<Integer> values) {
            addCriterion("product_tax_id not in", values, "productTaxId");
            return (Criteria) this;
        }

        public Criteria andProductTaxIdBetween(Integer value1, Integer value2) {
            addCriterion("product_tax_id between", value1, value2, "productTaxId");
            return (Criteria) this;
        }

        public Criteria andProductTaxIdNotBetween(Integer value1, Integer value2) {
            addCriterion("product_tax_id not between", value1, value2, "productTaxId");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNull() {
            addCriterion("audit_status is null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNotNull() {
            addCriterion("audit_status is not null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusEqualTo(String value) {
            addCriterion("audit_status =", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotEqualTo(String value) {
            addCriterion("audit_status <>", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThan(String value) {
            addCriterion("audit_status >", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThanOrEqualTo(String value) {
            addCriterion("audit_status >=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThan(String value) {
            addCriterion("audit_status <", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThanOrEqualTo(String value) {
            addCriterion("audit_status <=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLike(String value) {
            addCriterion("audit_status like", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotLike(String value) {
            addCriterion("audit_status not like", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIn(List<String> values) {
            addCriterion("audit_status in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotIn(List<String> values) {
            addCriterion("audit_status not in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusBetween(String value1, String value2) {
            addCriterion("audit_status between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotBetween(String value1, String value2) {
            addCriterion("audit_status not between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditBillIdIsNull() {
            addCriterion("audit_bill_id is null");
            return (Criteria) this;
        }

        public Criteria andAuditBillIdIsNotNull() {
            addCriterion("audit_bill_id is not null");
            return (Criteria) this;
        }

        public Criteria andAuditBillIdEqualTo(Long value) {
            addCriterion("audit_bill_id =", value, "auditBillId");
            return (Criteria) this;
        }

        public Criteria andAuditBillIdNotEqualTo(Long value) {
            addCriterion("audit_bill_id <>", value, "auditBillId");
            return (Criteria) this;
        }

        public Criteria andAuditBillIdGreaterThan(Long value) {
            addCriterion("audit_bill_id >", value, "auditBillId");
            return (Criteria) this;
        }

        public Criteria andAuditBillIdGreaterThanOrEqualTo(Long value) {
            addCriterion("audit_bill_id >=", value, "auditBillId");
            return (Criteria) this;
        }

        public Criteria andAuditBillIdLessThan(Long value) {
            addCriterion("audit_bill_id <", value, "auditBillId");
            return (Criteria) this;
        }

        public Criteria andAuditBillIdLessThanOrEqualTo(Long value) {
            addCriterion("audit_bill_id <=", value, "auditBillId");
            return (Criteria) this;
        }

        public Criteria andAuditBillIdIn(List<Long> values) {
            addCriterion("audit_bill_id in", values, "auditBillId");
            return (Criteria) this;
        }

        public Criteria andAuditBillIdNotIn(List<Long> values) {
            addCriterion("audit_bill_id not in", values, "auditBillId");
            return (Criteria) this;
        }

        public Criteria andAuditBillIdBetween(Long value1, Long value2) {
            addCriterion("audit_bill_id between", value1, value2, "auditBillId");
            return (Criteria) this;
        }

        public Criteria andAuditBillIdNotBetween(Long value1, Long value2) {
            addCriterion("audit_bill_id not between", value1, value2, "auditBillId");
            return (Criteria) this;
        }

        public Criteria andIsForecastIsNull() {
            addCriterion("is_forecast is null");
            return (Criteria) this;
        }

        public Criteria andIsForecastIsNotNull() {
            addCriterion("is_forecast is not null");
            return (Criteria) this;
        }

        public Criteria andIsForecastEqualTo(Byte value) {
            addCriterion("is_forecast =", value, "isForecast");
            return (Criteria) this;
        }

        public Criteria andIsForecastNotEqualTo(Byte value) {
            addCriterion("is_forecast <>", value, "isForecast");
            return (Criteria) this;
        }

        public Criteria andIsForecastGreaterThan(Byte value) {
            addCriterion("is_forecast >", value, "isForecast");
            return (Criteria) this;
        }

        public Criteria andIsForecastGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_forecast >=", value, "isForecast");
            return (Criteria) this;
        }

        public Criteria andIsForecastLessThan(Byte value) {
            addCriterion("is_forecast <", value, "isForecast");
            return (Criteria) this;
        }

        public Criteria andIsForecastLessThanOrEqualTo(Byte value) {
            addCriterion("is_forecast <=", value, "isForecast");
            return (Criteria) this;
        }

        public Criteria andIsForecastIn(List<Byte> values) {
            addCriterion("is_forecast in", values, "isForecast");
            return (Criteria) this;
        }

        public Criteria andIsForecastNotIn(List<Byte> values) {
            addCriterion("is_forecast not in", values, "isForecast");
            return (Criteria) this;
        }

        public Criteria andIsForecastBetween(Byte value1, Byte value2) {
            addCriterion("is_forecast between", value1, value2, "isForecast");
            return (Criteria) this;
        }

        public Criteria andIsForecastNotBetween(Byte value1, Byte value2) {
            addCriterion("is_forecast not between", value1, value2, "isForecast");
            return (Criteria) this;
        }

        public Criteria andNewArrivalTypeIsNull() {
            addCriterion("new_arrival_type is null");
            return (Criteria) this;
        }

        public Criteria andNewArrivalTypeIsNotNull() {
            addCriterion("new_arrival_type is not null");
            return (Criteria) this;
        }

        public Criteria andNewArrivalTypeEqualTo(String value) {
            addCriterion("new_arrival_type =", value, "newArrivalType");
            return (Criteria) this;
        }

        public Criteria andNewArrivalTypeNotEqualTo(String value) {
            addCriterion("new_arrival_type <>", value, "newArrivalType");
            return (Criteria) this;
        }

        public Criteria andNewArrivalTypeGreaterThan(String value) {
            addCriterion("new_arrival_type >", value, "newArrivalType");
            return (Criteria) this;
        }

        public Criteria andNewArrivalTypeGreaterThanOrEqualTo(String value) {
            addCriterion("new_arrival_type >=", value, "newArrivalType");
            return (Criteria) this;
        }

        public Criteria andNewArrivalTypeLessThan(String value) {
            addCriterion("new_arrival_type <", value, "newArrivalType");
            return (Criteria) this;
        }

        public Criteria andNewArrivalTypeLessThanOrEqualTo(String value) {
            addCriterion("new_arrival_type <=", value, "newArrivalType");
            return (Criteria) this;
        }

        public Criteria andNewArrivalTypeLike(String value) {
            addCriterion("new_arrival_type like", value, "newArrivalType");
            return (Criteria) this;
        }

        public Criteria andNewArrivalTypeNotLike(String value) {
            addCriterion("new_arrival_type not like", value, "newArrivalType");
            return (Criteria) this;
        }

        public Criteria andNewArrivalTypeIn(List<String> values) {
            addCriterion("new_arrival_type in", values, "newArrivalType");
            return (Criteria) this;
        }

        public Criteria andNewArrivalTypeNotIn(List<String> values) {
            addCriterion("new_arrival_type not in", values, "newArrivalType");
            return (Criteria) this;
        }

        public Criteria andNewArrivalTypeBetween(String value1, String value2) {
            addCriterion("new_arrival_type between", value1, value2, "newArrivalType");
            return (Criteria) this;
        }

        public Criteria andNewArrivalTypeNotBetween(String value1, String value2) {
            addCriterion("new_arrival_type not between", value1, value2, "newArrivalType");
            return (Criteria) this;
        }

        public Criteria andSeasonalIsNull() {
            addCriterion("seasonal is null");
            return (Criteria) this;
        }

        public Criteria andSeasonalIsNotNull() {
            addCriterion("seasonal is not null");
            return (Criteria) this;
        }

        public Criteria andSeasonalEqualTo(String value) {
            addCriterion("seasonal =", value, "seasonal");
            return (Criteria) this;
        }

        public Criteria andSeasonalNotEqualTo(String value) {
            addCriterion("seasonal <>", value, "seasonal");
            return (Criteria) this;
        }

        public Criteria andSeasonalGreaterThan(String value) {
            addCriterion("seasonal >", value, "seasonal");
            return (Criteria) this;
        }

        public Criteria andSeasonalGreaterThanOrEqualTo(String value) {
            addCriterion("seasonal >=", value, "seasonal");
            return (Criteria) this;
        }

        public Criteria andSeasonalLessThan(String value) {
            addCriterion("seasonal <", value, "seasonal");
            return (Criteria) this;
        }

        public Criteria andSeasonalLessThanOrEqualTo(String value) {
            addCriterion("seasonal <=", value, "seasonal");
            return (Criteria) this;
        }

        public Criteria andSeasonalLike(String value) {
            addCriterion("seasonal like", value, "seasonal");
            return (Criteria) this;
        }

        public Criteria andSeasonalNotLike(String value) {
            addCriterion("seasonal not like", value, "seasonal");
            return (Criteria) this;
        }

        public Criteria andSeasonalIn(List<String> values) {
            addCriterion("seasonal in", values, "seasonal");
            return (Criteria) this;
        }

        public Criteria andSeasonalNotIn(List<String> values) {
            addCriterion("seasonal not in", values, "seasonal");
            return (Criteria) this;
        }

        public Criteria andSeasonalBetween(String value1, String value2) {
            addCriterion("seasonal between", value1, value2, "seasonal");
            return (Criteria) this;
        }

        public Criteria andSeasonalNotBetween(String value1, String value2) {
            addCriterion("seasonal not between", value1, value2, "seasonal");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_hq_product
     *
     * @mbg.generated do_not_delete_during_merge Wed Sep 18 16:26:51 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}