package com.dailuobo.api.domain.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TblCityProductPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.city_product_id
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Integer cityProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.city_id
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.hq_product_id
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Integer hqProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.product_no
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private String productNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.hq_status
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Byte hqStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.city_status
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Byte cityStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.show_name
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private String showName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.disable_price
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private BigDecimal disablePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.weight_unit
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private String weightUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.num_unit
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private String numUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.origin
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private String origin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.advise_price
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private BigDecimal advisePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.remark
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.subtitle
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private String subtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.keyword
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private String keyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.icon_tip
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private String iconTip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.l1_l2_names
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private String l1L2Names;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.delivery_mode
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Byte deliveryMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.city_product_icon
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private String cityProductIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.city_product_pic
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private String cityProductPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.detail_url
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private String detailUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.home_flag
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Byte homeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.del_flag
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Byte delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.create_user_id
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.create_time
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.update_user_id
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Integer updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.update_time
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.purchase_factor
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Integer purchaseFactor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.is_share
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Integer isShare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.new_user_pro
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Byte newUserPro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.is_under
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Integer isUnder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.bar_code
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private String barCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.keep_type
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Integer keepType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.vip_limit
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Byte vipLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.quality_time
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Integer qualityTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.length
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private String length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.wide
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private String wide;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.high
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private String high;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.goods_type
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Byte goodsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.point_price
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Integer pointPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.point_mall_status
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Integer pointMallStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_city_product.last_vip_limit
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    private Byte lastVipLimit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.city_product_id
     *
     * @return the value of tbl_city_product.city_product_id
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Integer getCityProductId() {
        return cityProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.city_product_id
     *
     * @param cityProductId the value for tbl_city_product.city_product_id
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setCityProductId(Integer cityProductId) {
        this.cityProductId = cityProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.city_id
     *
     * @return the value of tbl_city_product.city_id
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.city_id
     *
     * @param cityId the value for tbl_city_product.city_id
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.hq_product_id
     *
     * @return the value of tbl_city_product.hq_product_id
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Integer getHqProductId() {
        return hqProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.hq_product_id
     *
     * @param hqProductId the value for tbl_city_product.hq_product_id
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setHqProductId(Integer hqProductId) {
        this.hqProductId = hqProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.product_no
     *
     * @return the value of tbl_city_product.product_no
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.product_no
     *
     * @param productNo the value for tbl_city_product.product_no
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.hq_status
     *
     * @return the value of tbl_city_product.hq_status
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Byte getHqStatus() {
        return hqStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.hq_status
     *
     * @param hqStatus the value for tbl_city_product.hq_status
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setHqStatus(Byte hqStatus) {
        this.hqStatus = hqStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.city_status
     *
     * @return the value of tbl_city_product.city_status
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Byte getCityStatus() {
        return cityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.city_status
     *
     * @param cityStatus the value for tbl_city_product.city_status
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setCityStatus(Byte cityStatus) {
        this.cityStatus = cityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.show_name
     *
     * @return the value of tbl_city_product.show_name
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public String getShowName() {
        return showName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.show_name
     *
     * @param showName the value for tbl_city_product.show_name
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setShowName(String showName) {
        this.showName = showName == null ? null : showName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.disable_price
     *
     * @return the value of tbl_city_product.disable_price
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public BigDecimal getDisablePrice() {
        return disablePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.disable_price
     *
     * @param disablePrice the value for tbl_city_product.disable_price
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setDisablePrice(BigDecimal disablePrice) {
        this.disablePrice = disablePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.weight_unit
     *
     * @return the value of tbl_city_product.weight_unit
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public String getWeightUnit() {
        return weightUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.weight_unit
     *
     * @param weightUnit the value for tbl_city_product.weight_unit
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setWeightUnit(String weightUnit) {
        this.weightUnit = weightUnit == null ? null : weightUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.num_unit
     *
     * @return the value of tbl_city_product.num_unit
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public String getNumUnit() {
        return numUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.num_unit
     *
     * @param numUnit the value for tbl_city_product.num_unit
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setNumUnit(String numUnit) {
        this.numUnit = numUnit == null ? null : numUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.origin
     *
     * @return the value of tbl_city_product.origin
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.origin
     *
     * @param origin the value for tbl_city_product.origin
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.advise_price
     *
     * @return the value of tbl_city_product.advise_price
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public BigDecimal getAdvisePrice() {
        return advisePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.advise_price
     *
     * @param advisePrice the value for tbl_city_product.advise_price
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setAdvisePrice(BigDecimal advisePrice) {
        this.advisePrice = advisePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.remark
     *
     * @return the value of tbl_city_product.remark
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.remark
     *
     * @param remark the value for tbl_city_product.remark
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.subtitle
     *
     * @return the value of tbl_city_product.subtitle
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.subtitle
     *
     * @param subtitle the value for tbl_city_product.subtitle
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.keyword
     *
     * @return the value of tbl_city_product.keyword
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.keyword
     *
     * @param keyword the value for tbl_city_product.keyword
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.icon_tip
     *
     * @return the value of tbl_city_product.icon_tip
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public String getIconTip() {
        return iconTip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.icon_tip
     *
     * @param iconTip the value for tbl_city_product.icon_tip
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setIconTip(String iconTip) {
        this.iconTip = iconTip == null ? null : iconTip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.l1_l2_names
     *
     * @return the value of tbl_city_product.l1_l2_names
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public String getL1L2Names() {
        return l1L2Names;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.l1_l2_names
     *
     * @param l1L2Names the value for tbl_city_product.l1_l2_names
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setL1L2Names(String l1L2Names) {
        this.l1L2Names = l1L2Names == null ? null : l1L2Names.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.delivery_mode
     *
     * @return the value of tbl_city_product.delivery_mode
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Byte getDeliveryMode() {
        return deliveryMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.delivery_mode
     *
     * @param deliveryMode the value for tbl_city_product.delivery_mode
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setDeliveryMode(Byte deliveryMode) {
        this.deliveryMode = deliveryMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.city_product_icon
     *
     * @return the value of tbl_city_product.city_product_icon
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public String getCityProductIcon() {
        return cityProductIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.city_product_icon
     *
     * @param cityProductIcon the value for tbl_city_product.city_product_icon
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setCityProductIcon(String cityProductIcon) {
        this.cityProductIcon = cityProductIcon == null ? null : cityProductIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.city_product_pic
     *
     * @return the value of tbl_city_product.city_product_pic
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public String getCityProductPic() {
        return cityProductPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.city_product_pic
     *
     * @param cityProductPic the value for tbl_city_product.city_product_pic
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setCityProductPic(String cityProductPic) {
        this.cityProductPic = cityProductPic == null ? null : cityProductPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.detail_url
     *
     * @return the value of tbl_city_product.detail_url
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public String getDetailUrl() {
        return detailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.detail_url
     *
     * @param detailUrl the value for tbl_city_product.detail_url
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setDetailUrl(String detailUrl) {
        this.detailUrl = detailUrl == null ? null : detailUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.home_flag
     *
     * @return the value of tbl_city_product.home_flag
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Byte getHomeFlag() {
        return homeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.home_flag
     *
     * @param homeFlag the value for tbl_city_product.home_flag
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setHomeFlag(Byte homeFlag) {
        this.homeFlag = homeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.del_flag
     *
     * @return the value of tbl_city_product.del_flag
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.del_flag
     *
     * @param delFlag the value for tbl_city_product.del_flag
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.create_user_id
     *
     * @return the value of tbl_city_product.create_user_id
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.create_user_id
     *
     * @param createUserId the value for tbl_city_product.create_user_id
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.create_time
     *
     * @return the value of tbl_city_product.create_time
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.create_time
     *
     * @param createTime the value for tbl_city_product.create_time
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.update_user_id
     *
     * @return the value of tbl_city_product.update_user_id
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.update_user_id
     *
     * @param updateUserId the value for tbl_city_product.update_user_id
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.update_time
     *
     * @return the value of tbl_city_product.update_time
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.update_time
     *
     * @param updateTime the value for tbl_city_product.update_time
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.purchase_factor
     *
     * @return the value of tbl_city_product.purchase_factor
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Integer getPurchaseFactor() {
        return purchaseFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.purchase_factor
     *
     * @param purchaseFactor the value for tbl_city_product.purchase_factor
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setPurchaseFactor(Integer purchaseFactor) {
        this.purchaseFactor = purchaseFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.is_share
     *
     * @return the value of tbl_city_product.is_share
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Integer getIsShare() {
        return isShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.is_share
     *
     * @param isShare the value for tbl_city_product.is_share
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setIsShare(Integer isShare) {
        this.isShare = isShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.new_user_pro
     *
     * @return the value of tbl_city_product.new_user_pro
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Byte getNewUserPro() {
        return newUserPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.new_user_pro
     *
     * @param newUserPro the value for tbl_city_product.new_user_pro
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setNewUserPro(Byte newUserPro) {
        this.newUserPro = newUserPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.is_under
     *
     * @return the value of tbl_city_product.is_under
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Integer getIsUnder() {
        return isUnder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.is_under
     *
     * @param isUnder the value for tbl_city_product.is_under
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setIsUnder(Integer isUnder) {
        this.isUnder = isUnder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.bar_code
     *
     * @return the value of tbl_city_product.bar_code
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.bar_code
     *
     * @param barCode the value for tbl_city_product.bar_code
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode == null ? null : barCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.keep_type
     *
     * @return the value of tbl_city_product.keep_type
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Integer getKeepType() {
        return keepType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.keep_type
     *
     * @param keepType the value for tbl_city_product.keep_type
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setKeepType(Integer keepType) {
        this.keepType = keepType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.vip_limit
     *
     * @return the value of tbl_city_product.vip_limit
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Byte getVipLimit() {
        return vipLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.vip_limit
     *
     * @param vipLimit the value for tbl_city_product.vip_limit
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setVipLimit(Byte vipLimit) {
        this.vipLimit = vipLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.quality_time
     *
     * @return the value of tbl_city_product.quality_time
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Integer getQualityTime() {
        return qualityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.quality_time
     *
     * @param qualityTime the value for tbl_city_product.quality_time
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setQualityTime(Integer qualityTime) {
        this.qualityTime = qualityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.length
     *
     * @return the value of tbl_city_product.length
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public String getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.length
     *
     * @param length the value for tbl_city_product.length
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setLength(String length) {
        this.length = length == null ? null : length.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.wide
     *
     * @return the value of tbl_city_product.wide
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public String getWide() {
        return wide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.wide
     *
     * @param wide the value for tbl_city_product.wide
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setWide(String wide) {
        this.wide = wide == null ? null : wide.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.high
     *
     * @return the value of tbl_city_product.high
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public String getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.high
     *
     * @param high the value for tbl_city_product.high
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setHigh(String high) {
        this.high = high == null ? null : high.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.goods_type
     *
     * @return the value of tbl_city_product.goods_type
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Byte getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.goods_type
     *
     * @param goodsType the value for tbl_city_product.goods_type
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setGoodsType(Byte goodsType) {
        this.goodsType = goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.point_price
     *
     * @return the value of tbl_city_product.point_price
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Integer getPointPrice() {
        return pointPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.point_price
     *
     * @param pointPrice the value for tbl_city_product.point_price
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setPointPrice(Integer pointPrice) {
        this.pointPrice = pointPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.point_mall_status
     *
     * @return the value of tbl_city_product.point_mall_status
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Integer getPointMallStatus() {
        return pointMallStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.point_mall_status
     *
     * @param pointMallStatus the value for tbl_city_product.point_mall_status
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setPointMallStatus(Integer pointMallStatus) {
        this.pointMallStatus = pointMallStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_city_product.last_vip_limit
     *
     * @return the value of tbl_city_product.last_vip_limit
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public Byte getLastVipLimit() {
        return lastVipLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_city_product.last_vip_limit
     *
     * @param lastVipLimit the value for tbl_city_product.last_vip_limit
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    public void setLastVipLimit(Byte lastVipLimit) {
        this.lastVipLimit = lastVipLimit;
    }
}