package com.mallcai.biz.category.dao.mapper;

import com.mallcai.domain.dataobject.category.IcFrontCategory;
import com.mallcai.domain.dto.IcFrontCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IcFrontCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_front_category
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    long countByExample(IcFrontCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_front_category
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    int deleteByExample(IcFrontCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_front_category
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_front_category
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    int insert(IcFrontCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_front_category
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    int insertSelective(IcFrontCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_front_category
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    List<IcFrontCategory> selectByExample(IcFrontCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_front_category
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    IcFrontCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_front_category
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") IcFrontCategory record, @Param("example") IcFrontCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_front_category
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    int updateByExample(@Param("record") IcFrontCategory record, @Param("example") IcFrontCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_front_category
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    int updateByPrimaryKeySelective(IcFrontCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_front_category
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    int updateByPrimaryKey(IcFrontCategory record);
}