package com.mallcai.biz.category.dao.mapper;

import com.mallcai.domain.dataobject.category.IcHqFcategoryRelatedBcategory;
import com.mallcai.domain.dto.IcHqFcategoryRelatedBcategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IcHqFcategoryRelatedBcategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_bcategory
     *
     * @mbg.generated Thu Sep 05 11:36:26 CST 2019
     */
    long countByExample(IcHqFcategoryRelatedBcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_bcategory
     *
     * @mbg.generated Thu Sep 05 11:36:26 CST 2019
     */
    int deleteByExample(IcHqFcategoryRelatedBcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_bcategory
     *
     * @mbg.generated Thu Sep 05 11:36:26 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_bcategory
     *
     * @mbg.generated Thu Sep 05 11:36:26 CST 2019
     */
    int insert(IcHqFcategoryRelatedBcategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_bcategory
     *
     * @mbg.generated Thu Sep 05 11:36:26 CST 2019
     */
    int insertSelective(IcHqFcategoryRelatedBcategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_bcategory
     *
     * @mbg.generated Thu Sep 05 11:36:26 CST 2019
     */
    List<IcHqFcategoryRelatedBcategory> selectByExample(IcHqFcategoryRelatedBcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_bcategory
     *
     * @mbg.generated Thu Sep 05 11:36:26 CST 2019
     */
    IcHqFcategoryRelatedBcategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_bcategory
     *
     * @mbg.generated Thu Sep 05 11:36:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") IcHqFcategoryRelatedBcategory record, @Param("example") IcHqFcategoryRelatedBcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_bcategory
     *
     * @mbg.generated Thu Sep 05 11:36:26 CST 2019
     */
    int updateByExample(@Param("record") IcHqFcategoryRelatedBcategory record, @Param("example") IcHqFcategoryRelatedBcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_bcategory
     *
     * @mbg.generated Thu Sep 05 11:36:26 CST 2019
     */
    int updateByPrimaryKeySelective(IcHqFcategoryRelatedBcategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_bcategory
     *
     * @mbg.generated Thu Sep 05 11:36:26 CST 2019
     */
    int updateByPrimaryKey(IcHqFcategoryRelatedBcategory record);
}