package com.mallcai.biz.category.dao.mapper;

import com.mallcai.domain.dataobject.category.IcHqFcategoryRelatedHqProduct;
import com.mallcai.domain.dto.IcHqFcategoryRelatedHqProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IcHqFcategoryRelatedHqProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_hq_product
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    long countByExample(IcHqFcategoryRelatedHqProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_hq_product
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    int deleteByExample(IcHqFcategoryRelatedHqProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_hq_product
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_hq_product
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    int insert(IcHqFcategoryRelatedHqProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_hq_product
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    int insertSelective(IcHqFcategoryRelatedHqProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_hq_product
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    List<IcHqFcategoryRelatedHqProduct> selectByExample(IcHqFcategoryRelatedHqProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_hq_product
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    IcHqFcategoryRelatedHqProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_hq_product
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") IcHqFcategoryRelatedHqProduct record, @Param("example") IcHqFcategoryRelatedHqProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_hq_product
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    int updateByExample(@Param("record") IcHqFcategoryRelatedHqProduct record, @Param("example") IcHqFcategoryRelatedHqProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_hq_product
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    int updateByPrimaryKeySelective(IcHqFcategoryRelatedHqProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_related_hq_product
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    int updateByPrimaryKey(IcHqFcategoryRelatedHqProduct record);
}