package com.mallcai.biz.category.dao.mapper;

import com.mallcai.domain.dataobject.category.IcHqFcategoryRelation;
import com.mallcai.domain.dto.IcHqFcategoryRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IcHqFcategoryRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_relation
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    long countByExample(IcHqFcategoryRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_relation
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    int deleteByExample(IcHqFcategoryRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_relation
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_relation
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    int insert(IcHqFcategoryRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_relation
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    int insertSelective(IcHqFcategoryRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_relation
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    List<IcHqFcategoryRelation> selectByExample(IcHqFcategoryRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_relation
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    IcHqFcategoryRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_relation
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") IcHqFcategoryRelation record, @Param("example") IcHqFcategoryRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_relation
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    int updateByExample(@Param("record") IcHqFcategoryRelation record, @Param("example") IcHqFcategoryRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_relation
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    int updateByPrimaryKeySelective(IcHqFcategoryRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_hq_fcategory_relation
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    int updateByPrimaryKey(IcHqFcategoryRelation record);
}