package com.mallcai.domain.dataobject.product;

import java.util.Date;

public class TblProductClassify {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_product_classify.classify_id
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    private Integer classifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_product_classify.classify_no
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    private String classifyNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_product_classify.classify_name
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    private String classifyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_product_classify.level
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    private Byte level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_product_classify.father_id
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    private Integer fatherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_product_classify.icon_url
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    private String iconUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_product_classify.del_flag
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    private Byte delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_product_classify.adjustment_factor
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    private Integer adjustmentFactor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_product_classify.create_user_id
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_product_classify.create_time
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_product_classify.update_user_id
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    private Integer updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_product_classify.update_time
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_product_classify.pickup_order
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    private Integer pickupOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_product_classify.show_order
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    private Integer showOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_product_classify.classify_id
     *
     * @return the value of tbl_product_classify.classify_id
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public Integer getClassifyId() {
        return classifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_product_classify.classify_id
     *
     * @param classifyId the value for tbl_product_classify.classify_id
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public void setClassifyId(Integer classifyId) {
        this.classifyId = classifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_product_classify.classify_no
     *
     * @return the value of tbl_product_classify.classify_no
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public String getClassifyNo() {
        return classifyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_product_classify.classify_no
     *
     * @param classifyNo the value for tbl_product_classify.classify_no
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public void setClassifyNo(String classifyNo) {
        this.classifyNo = classifyNo == null ? null : classifyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_product_classify.classify_name
     *
     * @return the value of tbl_product_classify.classify_name
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public String getClassifyName() {
        return classifyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_product_classify.classify_name
     *
     * @param classifyName the value for tbl_product_classify.classify_name
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public void setClassifyName(String classifyName) {
        this.classifyName = classifyName == null ? null : classifyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_product_classify.level
     *
     * @return the value of tbl_product_classify.level
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_product_classify.level
     *
     * @param level the value for tbl_product_classify.level
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_product_classify.father_id
     *
     * @return the value of tbl_product_classify.father_id
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public Integer getFatherId() {
        return fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_product_classify.father_id
     *
     * @param fatherId the value for tbl_product_classify.father_id
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public void setFatherId(Integer fatherId) {
        this.fatherId = fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_product_classify.icon_url
     *
     * @return the value of tbl_product_classify.icon_url
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_product_classify.icon_url
     *
     * @param iconUrl the value for tbl_product_classify.icon_url
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl == null ? null : iconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_product_classify.del_flag
     *
     * @return the value of tbl_product_classify.del_flag
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_product_classify.del_flag
     *
     * @param delFlag the value for tbl_product_classify.del_flag
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_product_classify.adjustment_factor
     *
     * @return the value of tbl_product_classify.adjustment_factor
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public Integer getAdjustmentFactor() {
        return adjustmentFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_product_classify.adjustment_factor
     *
     * @param adjustmentFactor the value for tbl_product_classify.adjustment_factor
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public void setAdjustmentFactor(Integer adjustmentFactor) {
        this.adjustmentFactor = adjustmentFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_product_classify.create_user_id
     *
     * @return the value of tbl_product_classify.create_user_id
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_product_classify.create_user_id
     *
     * @param createUserId the value for tbl_product_classify.create_user_id
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_product_classify.create_time
     *
     * @return the value of tbl_product_classify.create_time
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_product_classify.create_time
     *
     * @param createTime the value for tbl_product_classify.create_time
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_product_classify.update_user_id
     *
     * @return the value of tbl_product_classify.update_user_id
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_product_classify.update_user_id
     *
     * @param updateUserId the value for tbl_product_classify.update_user_id
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_product_classify.update_time
     *
     * @return the value of tbl_product_classify.update_time
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_product_classify.update_time
     *
     * @param updateTime the value for tbl_product_classify.update_time
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_product_classify.pickup_order
     *
     * @return the value of tbl_product_classify.pickup_order
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public Integer getPickupOrder() {
        return pickupOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_product_classify.pickup_order
     *
     * @param pickupOrder the value for tbl_product_classify.pickup_order
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public void setPickupOrder(Integer pickupOrder) {
        this.pickupOrder = pickupOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_product_classify.show_order
     *
     * @return the value of tbl_product_classify.show_order
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public Integer getShowOrder() {
        return showOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_product_classify.show_order
     *
     * @param showOrder the value for tbl_product_classify.show_order
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    public void setShowOrder(Integer showOrder) {
        this.showOrder = showOrder;
    }
}