package com.mallcai.bs.model;

import java.math.BigDecimal;
import java.util.Date;

public class TblHqProductPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.hq_product_id
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private Integer hqProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.classify_id
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private Integer classifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.product_no
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private String productNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.hq_product_name
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private String hqProductName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.remark
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.status
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.delivery_mode
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private Byte deliveryMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.hq_product_icon
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private String hqProductIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.hq_product_pic
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private String hqProductPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.localize_flag
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private Byte localizeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.del_flag
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private Byte delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.create_user_id
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.create_time
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.update_user_id
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private Integer updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.update_time
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.bar_code
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private String barCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.keep_type
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private Integer keepType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.quality_time
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private Integer qualityTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.is_standard
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private Integer isStandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.pick_classify
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private Integer pickClassify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.product_rate
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private BigDecimal productRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.length
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private String length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.wide
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private String wide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.high
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private String high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.goods_type
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private Byte goodsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.product_tax_id
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private Integer productTaxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.audit_status
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private String auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.audit_bill_id
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private Long auditBillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.is_forecast
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private Byte isForecast;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.new_arrival_type
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private String newArrivalType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hq_product.seasonal
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    private String seasonal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.hq_product_id
     *
     * @return the value of tbl_hq_product.hq_product_id
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public Integer getHqProductId() {
        return hqProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.hq_product_id
     *
     * @param hqProductId the value for tbl_hq_product.hq_product_id
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setHqProductId(Integer hqProductId) {
        this.hqProductId = hqProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.classify_id
     *
     * @return the value of tbl_hq_product.classify_id
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public Integer getClassifyId() {
        return classifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.classify_id
     *
     * @param classifyId the value for tbl_hq_product.classify_id
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setClassifyId(Integer classifyId) {
        this.classifyId = classifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.product_no
     *
     * @return the value of tbl_hq_product.product_no
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.product_no
     *
     * @param productNo the value for tbl_hq_product.product_no
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.hq_product_name
     *
     * @return the value of tbl_hq_product.hq_product_name
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public String getHqProductName() {
        return hqProductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.hq_product_name
     *
     * @param hqProductName the value for tbl_hq_product.hq_product_name
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setHqProductName(String hqProductName) {
        this.hqProductName = hqProductName == null ? null : hqProductName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.remark
     *
     * @return the value of tbl_hq_product.remark
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.remark
     *
     * @param remark the value for tbl_hq_product.remark
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.status
     *
     * @return the value of tbl_hq_product.status
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.status
     *
     * @param status the value for tbl_hq_product.status
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.delivery_mode
     *
     * @return the value of tbl_hq_product.delivery_mode
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public Byte getDeliveryMode() {
        return deliveryMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.delivery_mode
     *
     * @param deliveryMode the value for tbl_hq_product.delivery_mode
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setDeliveryMode(Byte deliveryMode) {
        this.deliveryMode = deliveryMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.hq_product_icon
     *
     * @return the value of tbl_hq_product.hq_product_icon
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public String getHqProductIcon() {
        return hqProductIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.hq_product_icon
     *
     * @param hqProductIcon the value for tbl_hq_product.hq_product_icon
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setHqProductIcon(String hqProductIcon) {
        this.hqProductIcon = hqProductIcon == null ? null : hqProductIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.hq_product_pic
     *
     * @return the value of tbl_hq_product.hq_product_pic
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public String getHqProductPic() {
        return hqProductPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.hq_product_pic
     *
     * @param hqProductPic the value for tbl_hq_product.hq_product_pic
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setHqProductPic(String hqProductPic) {
        this.hqProductPic = hqProductPic == null ? null : hqProductPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.localize_flag
     *
     * @return the value of tbl_hq_product.localize_flag
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public Byte getLocalizeFlag() {
        return localizeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.localize_flag
     *
     * @param localizeFlag the value for tbl_hq_product.localize_flag
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setLocalizeFlag(Byte localizeFlag) {
        this.localizeFlag = localizeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.del_flag
     *
     * @return the value of tbl_hq_product.del_flag
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.del_flag
     *
     * @param delFlag the value for tbl_hq_product.del_flag
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.create_user_id
     *
     * @return the value of tbl_hq_product.create_user_id
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.create_user_id
     *
     * @param createUserId the value for tbl_hq_product.create_user_id
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.create_time
     *
     * @return the value of tbl_hq_product.create_time
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.create_time
     *
     * @param createTime the value for tbl_hq_product.create_time
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.update_user_id
     *
     * @return the value of tbl_hq_product.update_user_id
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.update_user_id
     *
     * @param updateUserId the value for tbl_hq_product.update_user_id
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.update_time
     *
     * @return the value of tbl_hq_product.update_time
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.update_time
     *
     * @param updateTime the value for tbl_hq_product.update_time
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.bar_code
     *
     * @return the value of tbl_hq_product.bar_code
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.bar_code
     *
     * @param barCode the value for tbl_hq_product.bar_code
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode == null ? null : barCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.keep_type
     *
     * @return the value of tbl_hq_product.keep_type
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public Integer getKeepType() {
        return keepType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.keep_type
     *
     * @param keepType the value for tbl_hq_product.keep_type
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setKeepType(Integer keepType) {
        this.keepType = keepType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.quality_time
     *
     * @return the value of tbl_hq_product.quality_time
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public Integer getQualityTime() {
        return qualityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.quality_time
     *
     * @param qualityTime the value for tbl_hq_product.quality_time
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setQualityTime(Integer qualityTime) {
        this.qualityTime = qualityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.is_standard
     *
     * @return the value of tbl_hq_product.is_standard
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public Integer getIsStandard() {
        return isStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.is_standard
     *
     * @param isStandard the value for tbl_hq_product.is_standard
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setIsStandard(Integer isStandard) {
        this.isStandard = isStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.pick_classify
     *
     * @return the value of tbl_hq_product.pick_classify
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public Integer getPickClassify() {
        return pickClassify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.pick_classify
     *
     * @param pickClassify the value for tbl_hq_product.pick_classify
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setPickClassify(Integer pickClassify) {
        this.pickClassify = pickClassify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.product_rate
     *
     * @return the value of tbl_hq_product.product_rate
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public BigDecimal getProductRate() {
        return productRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.product_rate
     *
     * @param productRate the value for tbl_hq_product.product_rate
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setProductRate(BigDecimal productRate) {
        this.productRate = productRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.length
     *
     * @return the value of tbl_hq_product.length
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public String getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.length
     *
     * @param length the value for tbl_hq_product.length
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setLength(String length) {
        this.length = length == null ? null : length.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.wide
     *
     * @return the value of tbl_hq_product.wide
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public String getWide() {
        return wide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.wide
     *
     * @param wide the value for tbl_hq_product.wide
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setWide(String wide) {
        this.wide = wide == null ? null : wide.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.high
     *
     * @return the value of tbl_hq_product.high
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public String getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.high
     *
     * @param high the value for tbl_hq_product.high
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setHigh(String high) {
        this.high = high == null ? null : high.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.goods_type
     *
     * @return the value of tbl_hq_product.goods_type
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public Byte getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.goods_type
     *
     * @param goodsType the value for tbl_hq_product.goods_type
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setGoodsType(Byte goodsType) {
        this.goodsType = goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.product_tax_id
     *
     * @return the value of tbl_hq_product.product_tax_id
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public Integer getProductTaxId() {
        return productTaxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.product_tax_id
     *
     * @param productTaxId the value for tbl_hq_product.product_tax_id
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setProductTaxId(Integer productTaxId) {
        this.productTaxId = productTaxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.audit_status
     *
     * @return the value of tbl_hq_product.audit_status
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.audit_status
     *
     * @param auditStatus the value for tbl_hq_product.audit_status
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus == null ? null : auditStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.audit_bill_id
     *
     * @return the value of tbl_hq_product.audit_bill_id
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public Long getAuditBillId() {
        return auditBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.audit_bill_id
     *
     * @param auditBillId the value for tbl_hq_product.audit_bill_id
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setAuditBillId(Long auditBillId) {
        this.auditBillId = auditBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.is_forecast
     *
     * @return the value of tbl_hq_product.is_forecast
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public Byte getIsForecast() {
        return isForecast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.is_forecast
     *
     * @param isForecast the value for tbl_hq_product.is_forecast
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setIsForecast(Byte isForecast) {
        this.isForecast = isForecast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.new_arrival_type
     *
     * @return the value of tbl_hq_product.new_arrival_type
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public String getNewArrivalType() {
        return newArrivalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.new_arrival_type
     *
     * @param newArrivalType the value for tbl_hq_product.new_arrival_type
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setNewArrivalType(String newArrivalType) {
        this.newArrivalType = newArrivalType == null ? null : newArrivalType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hq_product.seasonal
     *
     * @return the value of tbl_hq_product.seasonal
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public String getSeasonal() {
        return seasonal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hq_product.seasonal
     *
     * @param seasonal the value for tbl_hq_product.seasonal
     *
     * @mbg.generated Wed Sep 18 16:26:51 CST 2019
     */
    public void setSeasonal(String seasonal) {
        this.seasonal = seasonal == null ? null : seasonal.trim();
    }
}