package com.mallcai.biz.product.dao.mapper;

import java.util.List;

import com.mallcai.domain.dataobject.product.TblCityProduct;
import com.mallcai.domain.dto.TblCityProductExample;
import org.apache.ibatis.annotations.Param;

public interface TblCityProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_city_product
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    long countByExample(TblCityProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_city_product
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    int deleteByExample(TblCityProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_city_product
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    int deleteByPrimaryKey(Integer cityProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_city_product
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    int insert(TblCityProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_city_product
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    int insertSelective(TblCityProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_city_product
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    List<TblCityProduct> selectByExample(TblCityProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_city_product
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    TblCityProduct selectByPrimaryKey(Integer cityProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_city_product
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") TblCityProduct record, @Param("example") TblCityProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_city_product
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    int updateByExample(@Param("record") TblCityProduct record, @Param("example") TblCityProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_city_product
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    int updateByPrimaryKeySelective(TblCityProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_city_product
     *
     * @mbg.generated Thu Jul 04 17:52:20 CST 2019
     */
    int updateByPrimaryKey(TblCityProduct record);
}
