package com.mallcai.biz.product.dao.mapper;

import com.mallcai.biz.product.model.HqProductCheckDO;
import com.mallcai.domain.dataobject.product.TblHqProduct;
import com.mallcai.domain.dto.TblHqProductExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblHqProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 04 17:25:25 CST 2019
     */
    long countByExample(TblHqProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 04 17:25:25 CST 2019
     */
    int deleteByExample(TblHqProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 04 17:25:25 CST 2019
     */
    int deleteByPrimaryKey(Integer hqProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 04 17:25:25 CST 2019
     */
    int insert(TblHqProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 04 17:25:25 CST 2019
     */
    int insertSelective(TblHqProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 04 17:25:25 CST 2019
     */
    List<TblHqProduct> selectByExample(TblHqProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 04 17:25:25 CST 2019
     */
    TblHqProduct selectByPrimaryKey(Integer hqProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 04 17:25:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") TblHqProduct record, @Param("example") TblHqProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 04 17:25:25 CST 2019
     */
    int updateByExample(@Param("record") TblHqProduct record, @Param("example") TblHqProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 04 17:25:25 CST 2019
     */
    int updateByPrimaryKeySelective(TblHqProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_hq_product
     *
     * @mbg.generated Wed Sep 04 17:25:25 CST 2019
     */
    int updateByPrimaryKey(TblHqProduct record);


    List<TblHqProduct> selectByKeyWord(@Param("keyword") String keyword);


    TblHqProduct selectByItemId(@Param("itemId") Long itemId,@Param("productNo")String productNo);


    List<TblHqProduct> checkDumpHqProduct(@Param("list")List<HqProductCheckDO> list);
}
