package com.mallcai.biz.product.dao.mapper;

import com.mallcai.domain.dataobject.product.TblProductClassify;
import com.mallcai.domain.dto.TblProductClassifyExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TblProductClassifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_classify
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    long countByExample(TblProductClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_classify
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    int deleteByExample(TblProductClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_classify
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    int deleteByPrimaryKey(Integer classifyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_classify
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    int insert(TblProductClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_classify
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    int insertSelective(TblProductClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_classify
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    List<TblProductClassify> selectByExample(TblProductClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_classify
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    TblProductClassify selectByPrimaryKey(Integer classifyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_classify
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") TblProductClassify record, @Param("example") TblProductClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_classify
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    int updateByExample(@Param("record") TblProductClassify record, @Param("example") TblProductClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_classify
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    int updateByPrimaryKeySelective(TblProductClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_classify
     *
     * @mbg.generated Thu Jul 04 18:27:52 CST 2019
     */
    int updateByPrimaryKey(TblProductClassify record);
}
