package com.mallcai.domain.dataobject.category;

import java.util.Date;

public class IcFrontCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_front_category.id
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_front_category.name
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_front_category.level
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_front_category.parent_id
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_front_category.status
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_front_category.display_order
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    private Integer displayOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_front_category.description
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_front_category.create_user_id
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_front_category.create_time
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_front_category.update_user_id
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    private Integer updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_front_category.update_time
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_front_category.is_deleted
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    private Byte isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_front_category.id
     *
     * @return the value of ic_front_category.id
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_front_category.id
     *
     * @param id the value for ic_front_category.id
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_front_category.name
     *
     * @return the value of ic_front_category.name
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_front_category.name
     *
     * @param name the value for ic_front_category.name
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_front_category.level
     *
     * @return the value of ic_front_category.level
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_front_category.level
     *
     * @param level the value for ic_front_category.level
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_front_category.parent_id
     *
     * @return the value of ic_front_category.parent_id
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_front_category.parent_id
     *
     * @param parentId the value for ic_front_category.parent_id
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_front_category.status
     *
     * @return the value of ic_front_category.status
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_front_category.status
     *
     * @param status the value for ic_front_category.status
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_front_category.display_order
     *
     * @return the value of ic_front_category.display_order
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_front_category.display_order
     *
     * @param displayOrder the value for ic_front_category.display_order
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_front_category.description
     *
     * @return the value of ic_front_category.description
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_front_category.description
     *
     * @param description the value for ic_front_category.description
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_front_category.create_user_id
     *
     * @return the value of ic_front_category.create_user_id
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_front_category.create_user_id
     *
     * @param createUserId the value for ic_front_category.create_user_id
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_front_category.create_time
     *
     * @return the value of ic_front_category.create_time
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_front_category.create_time
     *
     * @param createTime the value for ic_front_category.create_time
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_front_category.update_user_id
     *
     * @return the value of ic_front_category.update_user_id
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_front_category.update_user_id
     *
     * @param updateUserId the value for ic_front_category.update_user_id
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_front_category.update_time
     *
     * @return the value of ic_front_category.update_time
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_front_category.update_time
     *
     * @param updateTime the value for ic_front_category.update_time
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_front_category.is_deleted
     *
     * @return the value of ic_front_category.is_deleted
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_front_category.is_deleted
     *
     * @param isDeleted the value for ic_front_category.is_deleted
     *
     * @mbg.generated Thu Sep 05 11:35:42 CST 2019
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}