package com.mallcai.domain.dataobject.category;

import java.util.Date;

public class IcHqFcategoryRelatedHqProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_hq_fcategory_related_hq_product.id
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_hq_fcategory_related_hq_product.relation_id
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    private Long relationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_hq_fcategory_related_hq_product.hq_product_id
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    private Long hqProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_hq_fcategory_related_hq_product.product_no
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    private String productNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_hq_fcategory_related_hq_product.display_order
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    private Integer displayOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_hq_fcategory_related_hq_product.create_user_id
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_hq_fcategory_related_hq_product.create_time
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_hq_fcategory_related_hq_product.update_user_id
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    private Integer updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_hq_fcategory_related_hq_product.update_time
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_hq_fcategory_related_hq_product.is_deleted
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    private Byte isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_hq_fcategory_related_hq_product.id
     *
     * @return the value of ic_hq_fcategory_related_hq_product.id
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_hq_fcategory_related_hq_product.id
     *
     * @param id the value for ic_hq_fcategory_related_hq_product.id
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_hq_fcategory_related_hq_product.relation_id
     *
     * @return the value of ic_hq_fcategory_related_hq_product.relation_id
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    public Long getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_hq_fcategory_related_hq_product.relation_id
     *
     * @param relationId the value for ic_hq_fcategory_related_hq_product.relation_id
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    public void setRelationId(Long relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_hq_fcategory_related_hq_product.hq_product_id
     *
     * @return the value of ic_hq_fcategory_related_hq_product.hq_product_id
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    public Long getHqProductId() {
        return hqProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_hq_fcategory_related_hq_product.hq_product_id
     *
     * @param hqProductId the value for ic_hq_fcategory_related_hq_product.hq_product_id
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    public void setHqProductId(Long hqProductId) {
        this.hqProductId = hqProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_hq_fcategory_related_hq_product.product_no
     *
     * @return the value of ic_hq_fcategory_related_hq_product.product_no
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_hq_fcategory_related_hq_product.product_no
     *
     * @param productNo the value for ic_hq_fcategory_related_hq_product.product_no
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_hq_fcategory_related_hq_product.display_order
     *
     * @return the value of ic_hq_fcategory_related_hq_product.display_order
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_hq_fcategory_related_hq_product.display_order
     *
     * @param displayOrder the value for ic_hq_fcategory_related_hq_product.display_order
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_hq_fcategory_related_hq_product.create_user_id
     *
     * @return the value of ic_hq_fcategory_related_hq_product.create_user_id
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_hq_fcategory_related_hq_product.create_user_id
     *
     * @param createUserId the value for ic_hq_fcategory_related_hq_product.create_user_id
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_hq_fcategory_related_hq_product.create_time
     *
     * @return the value of ic_hq_fcategory_related_hq_product.create_time
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_hq_fcategory_related_hq_product.create_time
     *
     * @param createTime the value for ic_hq_fcategory_related_hq_product.create_time
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_hq_fcategory_related_hq_product.update_user_id
     *
     * @return the value of ic_hq_fcategory_related_hq_product.update_user_id
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_hq_fcategory_related_hq_product.update_user_id
     *
     * @param updateUserId the value for ic_hq_fcategory_related_hq_product.update_user_id
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_hq_fcategory_related_hq_product.update_time
     *
     * @return the value of ic_hq_fcategory_related_hq_product.update_time
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_hq_fcategory_related_hq_product.update_time
     *
     * @param updateTime the value for ic_hq_fcategory_related_hq_product.update_time
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_hq_fcategory_related_hq_product.is_deleted
     *
     * @return the value of ic_hq_fcategory_related_hq_product.is_deleted
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_hq_fcategory_related_hq_product.is_deleted
     *
     * @param isDeleted the value for ic_hq_fcategory_related_hq_product.is_deleted
     *
     * @mbg.generated Thu Sep 12 14:01:50 CST 2019
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}