package com.mallcai.domain.dataobject.category;

import java.util.Date;

public class IcHqFcategoryRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_hq_fcategory_relation.id
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_hq_fcategory_relation.front_category_id
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    private Long frontCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_hq_fcategory_relation.relation_type
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    private Integer relationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_hq_fcategory_relation.create_user_id
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_hq_fcategory_relation.create_time
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_hq_fcategory_relation.update_user_id
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    private Integer updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_hq_fcategory_relation.update_time
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_hq_fcategory_relation.is_deleted
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    private Byte isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_hq_fcategory_relation.id
     *
     * @return the value of ic_hq_fcategory_relation.id
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_hq_fcategory_relation.id
     *
     * @param id the value for ic_hq_fcategory_relation.id
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_hq_fcategory_relation.front_category_id
     *
     * @return the value of ic_hq_fcategory_relation.front_category_id
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    public Long getFrontCategoryId() {
        return frontCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_hq_fcategory_relation.front_category_id
     *
     * @param frontCategoryId the value for ic_hq_fcategory_relation.front_category_id
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    public void setFrontCategoryId(Long frontCategoryId) {
        this.frontCategoryId = frontCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_hq_fcategory_relation.relation_type
     *
     * @return the value of ic_hq_fcategory_relation.relation_type
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    public Integer getRelationType() {
        return relationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_hq_fcategory_relation.relation_type
     *
     * @param relationType the value for ic_hq_fcategory_relation.relation_type
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    public void setRelationType(Integer relationType) {
        this.relationType = relationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_hq_fcategory_relation.create_user_id
     *
     * @return the value of ic_hq_fcategory_relation.create_user_id
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_hq_fcategory_relation.create_user_id
     *
     * @param createUserId the value for ic_hq_fcategory_relation.create_user_id
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_hq_fcategory_relation.create_time
     *
     * @return the value of ic_hq_fcategory_relation.create_time
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_hq_fcategory_relation.create_time
     *
     * @param createTime the value for ic_hq_fcategory_relation.create_time
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_hq_fcategory_relation.update_user_id
     *
     * @return the value of ic_hq_fcategory_relation.update_user_id
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_hq_fcategory_relation.update_user_id
     *
     * @param updateUserId the value for ic_hq_fcategory_relation.update_user_id
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_hq_fcategory_relation.update_time
     *
     * @return the value of ic_hq_fcategory_relation.update_time
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_hq_fcategory_relation.update_time
     *
     * @param updateTime the value for ic_hq_fcategory_relation.update_time
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_hq_fcategory_relation.is_deleted
     *
     * @return the value of ic_hq_fcategory_relation.is_deleted
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_hq_fcategory_relation.is_deleted
     *
     * @param isDeleted the value for ic_hq_fcategory_relation.is_deleted
     *
     * @mbg.generated Thu Sep 05 11:36:06 CST 2019
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}